### ISSUE TITLE
Consider adding OrcaSlicer Support

### ISSUE THREAD

**Issue by spuder** [Ankermgmt/prusaslicer-ankermake-ce-profiles#18]
OrcaSlicer has native profiles for Anker. Consider adding support to the `install.sh` and `install.ps1`

## Key Differences

1. It appears that orcaslicer doesn't use the 'vendor' directory but install puts files directly in `ls ~/Library/Application\ Support/OrcaSlicer` (verify this)
2. 
![Screenshot 2023-05-15 at 2 42 38 PM](https://github.com/Ankermgmt/prusaslicer-ankermake-ce-profiles/assets/242382/f5b8556c-abbc-4497-a32f-e5f083b51b3e)

**Comment by just-trey** [comment]
They use a JSON format so it's not 1-1 compatible. Some variable names are different as well.

**Comment by spuder** [comment]
Good!? Ignoring it then
