### ISSUE TITLE
Can't import to AnkerMake slicer

### ISSUE THREAD

**Issue by Evo609** [Ankermgmt/prusaslicer-ankermake-ce-profiles#34]
Extract the zip file to a location of your choice and open the folder.
Open the AnkerMake Alpha slicer
**Go to File -> Import -> Import Config Bundle** - there is no such option.

Config file is not readable by ankermake slicer.

**Comment by Evo609** [comment]
I'm IQ2 :) Use AnkerMake Studio, not AnkerMake Slicer

**Comment by billyjbryant** [comment]
Currently `ankerctl` does not support the new AnkerMake Studio for login and authentication. We will be evaluating the changes necessary to shift to the new authentication mechanism
