### ISSUE TITLE
First layer problem -> Decrease first_layer_speed

### ISSUE THREAD

**Issue by HansAndreManfredson** [Ankermgmt/prusaslicer-ankermake-ce-profiles#35]
Hi @just-trey,
please change the following lines to

first_layer_speed = 50
first_layer_speed_over_raft = 50

The default value for the first_layer_speed in AnkerSlicer is 50 mm/s. Even in fast mode.
A first layer with a higher speed is not going to be successful.

I had a lot of trouble until I was able to use the profile in PrusaSlicer!
Now I will not go back to the AnkerSlicer...

Thanks for your work!

By the way: I just wanted to push a commit, but without a different branch or different rights it's not possible.

**Comment by garytube** [comment]
agree - now its 50% of 600mm/s which does not work at all
