### ISSUE TITLE
[Idea] Add install script

### ISSUE THREAD

**Issue by spuder** [Ankermgmt/prusaslicer-ankermake-ce-profiles#7]
These profiles are great. 
The process for installing them is prusa slicer is a little tedious. (Especially since newer and improved versions are coming out so often)

## Idea:

What if the vendor directory had an install script
```
./install.sh
./install.ps1
```

The script would
1. Detect OS
2. Attempt to find the folder for profiles
3. Copy the configs to the prusa slicer config directory

This could reduce friction for the end users and make it easier to stay up to date with the latest changes. 

(It may also pave the way for a full installer like hombrew, dpkg, ect... which would make this a 1 click install for users.)

I'm happy to implement this when I get some time, but first I'm looking to gauge feedback if others would find this desirable.

**Comment by just-trey** [comment]
I'm a +1 and would appreciate it.

**Comment by just-trey** [comment]
closed in [v2.2.0](https://github.com/Ankermgmt/prusaslicer-ankermake-ce-profiles/releases/tag/v2.2.0)

**Comment by just-trey** [comment]
closed in [v2.2.0](https://github.com/Ankermgmt/prusaslicer-ankermake-ce-profiles/releases/tag/v2.2.0)
