### ISSUE TITLE
PETG temperatures are too low

### ISSUE THREAD

**Issue by spuder** [Ankermgmt/prusaslicer-ankermake-ce-profiles#9]
I installed the 2.1.1 profiles, but I'm seeing that the default PETG settings are too low (`200/0`)

![Screenshot 2023-05-11 at 10 21 03 AM](https://github.com/Ankermgmt/prusaslicer-ankermake-ce-profiles/assets/242382/997260fb-bb2e-4211-8a6b-cbfc9917b322)

By contrast, the default PETG from Ankers Prusa Slicer is `240/70`

![Screenshot 2023-05-11 at 1 51 28 PM](https://github.com/Ankermgmt/prusaslicer-ankermake-ce-profiles/assets/242382/e8b0d057-a227-4ae4-80b7-5378d22305d4)

I've poked around the code, but I can't find where `200/0` comes from

**Comment by just-trey** [comment]
I'll fix this and close with the next release

**Comment by just-trey** [comment]
Closed in v2.2.0
